import { create } from 'zustand'
import { allSongs } from "@/lib/data";
const useMusicStore = create((set) => ({
    selectedPlaylist: allSongs,
    selectedSong: allSongs.dll.head.next.data,
    setSelectedPlaylist: (playlist) => set({ selectedPlaylist: playlist}),
    setSelectedSong: (song) => set({ selectedSong: song}),
    playFunction: null,
    setPlayFunction: (playFunction) => set({ playFunction: playFunction}),
    isPlaying: false,
    setIsPlaying: (isPlaying) => set({isPlaying: isPlaying}),
    toggleIsPlaying: () => set((state) => ({ isPlaying: !state.isPlaying })),
    originalPlaylist: allSongs,
    setOriginalPlaylist: (playlist) => set({ originalPlaylist: playlist}),
    isLooping: false,
    toggleIsLooping: () => set((state) => ({ isLooping: !state.isLooping })),
    isShuffling: false,
    toggleIsShuffling: () => set((state) => ({ isShuffling: !state.isShuffling })),
    reload: 0,
    setReload: () => set((state) => ({ reload: state.reload + 1 })),
    currentTime: 0,
    setCurrentTime: (currentTime) => set({currentTime: currentTime}),
    duration: 0,
    setDuration: (duration) => set({duration: duration}),
    addToList: false,
    toggleAddToList: () => set((state) => ({ addToList: !state.addToList })),
    songForAddToList: allSongs.dll.head.next.data,
    setSongForAddToList: (song) => set({ songForAddToList: song}),
//   bears: 0,
//   increasePopulation: () => set((state) => ({ bears: state.bears + 1 })),
//   removeAllBears: () => set({ bears: 0 }),
}))
export default useMusicStore;